config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end

  root 'tops#index'
  resources :tops, only: [:new, :create] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  protect_from_forgery except: :create

  def index
    @new_experience = Experience.order('created_at DESC')
  end

  def new
    @experience = Experience.new
    #セレクトボックスの初期値設定
    @industry_parent_array = [""]
    # categoriesから親カテゴリーの名前のみ抽出し、配列化
    Industry.where(ancestry: nil).each do |parent|
      @industry_parent_array << parent.name
    end
  end

  def create
    @experience = Experience.new(experience_params)
    if @experience.save
      redirect_to root_path
    else
      redirect_to new_top_path, notice: "必須項目は入力してください"
    end
  end

  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    Industry.find("#{params[:parent_id]}").children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    Industry.find("#{params[:child_id]}").children
  end


  private
  def experience_params
    params.require(:experience).permit(:company, :position, :title, :text, :price_id, :talk, :talk_time, :industry_id, :occupation, :prefecture_id, :image, :join_year, :join_month).merge(user_id: current_user.id)
  end
end

app/views/tops/index.html.haml
.Image01-content
  = image_tag 'top1.jpg', size: "1440x600", alt: "test", class: "Image01-content__image"
  .Textbox
    .Textbox__text
      転職を考えたら
      %br
      社会人こそOB訪問
    .Box
      .Box__content
        .Box__content--text
          国内最大級
      .Box__content
        .Box__content--text
          オンライン可
      .Box__content
        .Box__content--text
          独立・起業にも
    .Top
      .Top__text
        利用規約、個人情報保護方針に関して
    .Login
      =link_to '新規登録する・ログイン', new_user_registration_path, class:"Login__text"
.Image02-content
  .Center-content
    .Up-content
      .Box
        .Box__up
          = image_tag 'middle1.jpg', size: "215x170", alt: "test", class: "Image01-content__image"
        .Box__middle
          興味のあるキャリア経験談を
          %br
          聞こう！
        .Box__bottom
          さまざまな企業・職種・テーマに関するリ
          アルな情報を経験者から聞くことができま
          す。1クリックで始められるビデオ通話も
          搭載！
      .Box
        .Box__up
          = image_tag 'middle2.jpg', size: "215x170", alt: "test", class: "Image01-content__image"
        .Box__middle
          自分のキャリア経験談を
          %br
          話そう！
        .Box__bottom
          キャリア経験談を登録すると、話を聞きたい人から申し込みが届きます。
          テンプレートや例が表示されるので、経験談の登録はとてもかんたん！
      .Box
        .Box__up
          = image_tag 'middle3.jpg', size: "215x170", alt: "test", class: "Image01-content__image"
        .Box__middle
          気になる企業の社員と
          %br
          つながろう！
        .Box__bottom
          「メンバー募集中」ラベルをつけているユーザーと気軽にカジュアル面談
          してみましょう。特別な転職・副業オファーがもらえるかも！
    .Bottom-content
      .Bottom-content__text
        .Bottom-content__text--color
          はじめてのかたはこちら

.Middle-wrapper
  .Middle
    .Middle__text
      みんなの経験談をみてみよう！
  .Search-body
    .Header
      経験談を探す
    .Search
      フリーワードで探す
    = form_with url: "#", local: true, method: :get do |form|
      .Search-box
        .Search-box__input
          = form.text_field :keyword, class: 'Search-box__input--field', placeholder: '仕事を検索する'        
        .Search-box__button
          = form.submit '検索', class: 'Search-box__button--text'
    .Search
      ハッシュタグで探す
    .Tagu-box01
      .Tagu
        カテゴリタグ
      .Tagu-content
        .Tagu-content__box
          食品・自転車
        .Tagu-content__box
          食品・自転車
        .Tagu-content__box
          食品・自転車
        .Tagu-content__box
          食品・自転車
        .Tagu-content__box
          食品・自転車
        .Tagu-content__box
          食品・自転車
        .Tagu-content__box
          食品・自転車
        .Tagu-content__box
          食品・自転車
        .Tagu-content__box
          食品・自転車
        .Tagu-content__box
          食品・自転車
        .Tagu-content__box
          食品・自転車
        .Tagu-content__box
          食品・自転車
        .Tagu-content__box
          食品・自転車
      .Tagu
        職種タグ
      .Tagu-content
        .Tagu-content__box
          メーカー
        .Tagu-content__box
          メーカー
        .Tagu-content__box
          メーカー
        .Tagu-content__box
          メーカー
        .Tagu-content__box
          メーカー
        .Tagu-content__box
          メーカー
        .Tagu-content__box
          メーカー
        .Tagu-content__box
          メーカー
        .Tagu-content__box
          メーカー
        .Tagu-content__box
          メーカー
        .Tagu-content__box
          メーカー
        .Tagu-content__box
          メーカー
        .Tagu-content__box
          メーカー
      .Tagu
        都道府県
      .Tagu-content
        .Tagu-content__box
          北海道
        .Tagu-content__box
          青森県
        .Tagu-content__box
          岩手県
        .Tagu-content__box
          秋田県
        .Tagu-content__box
          福島県
  .Member-tag
    .Member-tag__text
      メンバー紹介
  .Cards-box
    - @new_experience.each do |experience|
      = link_to "#", class:"Card" do
        .Card-topic
          .Card-topic__title
            =experience.title
          .Topic-middle
            - if experience.talk == "true"
              .Topic-middle__red
                .Topic-middle__red--text
                  ビデオ通話のみ可能
            - else
              .Topic-middle__blue
                .Topic-middle__blue--text
                  対面で面会が可能
            .Topic-middle__right
              =experience.price.name
        .Topic-under
          .Topic-under__img
            =image_tag experience.image.url, size: "50x50", alt: "test", class: "Topic-under__img--file"
          .Topic-under__right
            .Topic-under__right--text
              =experience.company
            .Topic-under__right-info
              .Topic-under__right-info--text
                =experience.position 
              .Topic-under__right-info--text01
                =experience.occupation 
            .Topic-under__year
              =experience.join_year
              %span 年
              =experience.join_month
              %span 月〜

app/views/tops/new.html.haml
.Create-wrapper
  =form_with model: @experience, url: tops_path, local: true do |form|
    %h2.Title01
      経験談を登録する
    %h3.Title02
      どの経歴について話しますか？
    .Format
      .Format-content01
        %h4.Format-content01__left
          会社・所属組織名
        %h6.Format-content01__right
          必須
      .Input
        = form.text_field :company, class: 'Input__text', placeholder: 'type a message'
    .Format
      .Format-content01    
        %h4.Format-content01__left
          担当役職・肩書き
        %h6.Format-content01__right
          必須
      .Input
        = form.text_field :position, class: 'Input__text', placeholder: 'type a message'
    .Format
      .Format-content01    
        %h4.Format-content01__left
          職種を入力する
        %h6.Format-content01__right
          必須
      .Input
        = form.text_field :occupation, class: 'Input__text', placeholder: '例) 営業職'
    .Format
      .Format-content01    
        %h4.Format-content01__left
          所属年を記入する
        %h6.Format-content01__right
          必須
      .Input
        = form.text_field :join_year, class: 'Input__year', placeholder: '2020'
        %span 年
        = form.text_field :join_month, class: 'Input__month', placeholder: '4'
        %span 月
    %h4.Title03
      どんな内容について話しますか？
    .Example
      .Example-top
        %h4.Example-top__title
          どんな内容を話すか迷った時は？
        %h5.Example-top__text
          例えばこんな内容が登録されています！参考にしてみてください！
      .Example-middle
        %h4.Example-middle__title 
          会社・組織や仕事内容について話す
        %ul.Example-middle__sentence
          %li.Example-middle__sentence--text 
            所属している組織について話します。
          %li.Example-middle__sentence--text
            会社・組織の風土について話します。
          %li.Example-middle__sentence--text
            現在の仕事内容の厳しさについて話します。
          %li.Example-middle__sentence--text
            所属している会社での働き方について話します。
      .Example-middle
        %h4.Example-middle__title 
          業種・業態について話す
        %ul.Example-middle__sentence
          %li.Example-middle__sentence--text 
            業界全体像について話します！
          %li.Example-middle__sentence--text
            未経験からの転職事情についてはなします！
          %li.Example-middle__sentence--text
            未経験ならではの厳しさについて話します！
      .Example-middle
        %h4.Example-middle__title 
          キャリアパスについて話します！
        %ul.Example-middle__sentence
          %li.Example-middle__sentence--text 
            転職してわかったキャリア形成の仕方について話します！
          %li.Example-middle__sentence--text
            社内でのジョブチェンジについて話します！
          %li.Example-middle__sentence--text
            社会人留学について話します！
    .Format01
      .Format01-top
        .Format-content01
          %h4.Format-content01__left
            タイトル
          %h6.Format-content01__right
            必須
        %h6.Format-content02
          0/40
      .Input
        = form.text_field :title, class: 'Input__text', placeholder: 'type a message'
      .Text
        について話します！
    .Format02
      .Format-content01
        %h4.Format-content01__left
          詳細
        %h6.Format-content01__right
          0/400
      %h5.Format-content02
        経歴や内容の詳細、どんな人におすすめなのかなどを書きましょう！
      .Input
        = form.text_area :text, class: 'Input__area', maxlength: 400, placeholder: '例）大手製造業で商品企画を努めていましたが、自身のキャリアを見つめ直し、広告代理店へ転職しました。「未経験で転職するコツは？」「広告代理店って正直どうなの？」にお答えします'
      .Text
        について話します！
    .Format03
      .Format-content01    
        %h4.Format-content01__left
          表示アイコン
        %h6.Format-content01__right
          必須
      %h5.Format-content02
        ご自身の写真などを登録される方が申し込み数は増加しますのでおすすめです！
        %br
        写真以外のイラストなどでも構いません。
      .View_box
      .Preview
        = form.label :image, class: 'Preview__image' do
          .Preview__image--text アイコンを登録する
        = form.file_field :image, class: 'Preview__image--file'
    .Format03
      .Format-content01    
        %h4.Format-content01__left
          金額（30分あたり）
        %h6.Format-content01__right
          必須
      %h5.Format-content02
        通常は有料を選びます。より多くの申し込みがほしい場合は無料がおすすめです。
        %br
        経験談を話した回数が増えると、申し込み数が入りやすいです。
      .Input
        = form.collection_select :price_id, Price.all, :id, :name, {include_blank: "選択してください"}, {class: 'Input__text'}
    .Format04
      .Format-content01    
        %h4.Format-content01__left
          話す形式
      %h5.Format-content02
        通ビデオ通話または対面で話すことができます。
        %br
        ビデオ通話のみで話したい場合はチェックを入れてください。
      .Check
        = form.check_box :talk ,{checked: false}, "true", "false"
        %span ビデオ通話のみ可能
    .Format03
      .Format-content01
        %h4.Format-content01__left
          話す時間
      %h5.Format-content02
        30分から最長３時間まで（30分ごとに選択できます）
      .Input
        = form.number_field :talk_time, class: 'Input__text', placeholder: 'type a message', min: 30, max: 180
    .Format03-js
      .Format-content01    
        %h4.Format-content01__left
          業界（業種）を選択する
      %h5.Format-content02
        １つ選択してください
      .Input-js
        = form.collection_select :industry_id, Industry.roots, :id, :name, {prompt: '選択してください'}, {class: 'Input-js__text', id: 'parent-category'} 
    .Format03
      .Format-content01    
        %h4.Format-content01__left
          都道府県を選択する
      %h5.Format-content02
        現在働いている企業の都道府県を選択してください。
      .Input
        = form.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: "選択してください"}, {class: 'Input__text'}
    .Button-content
      = form.submit '内容を登録する', class: 'Button-content__btn'