config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end

  root 'tops#index'
  resources :tops, only: [:new, :create] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
    end
  end
end

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DirrentIndustires
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
  .Header
    .Center
      .Center-left
        .Center-left__logo
          CREEDO
      - unless user_signed_in?
        .Center-right
          =link_to 'Login', new_user_session_path, class:"Center-right__login"
      - else
        .Signed-in
          .Signed-in__content
            = link_to new_top_path, class: "Signed-in__content--link" do
              = icon('fas', 'edit', class: 'Signed-in__content--icon')
              %span.Signed-in__content--text 経験談を登録する
          .Signed-in__content
            = link_to "#", class: "Signed-in__content--link" do
              = icon('fas', 'comments', class: 'Signed-in__content--icon')
              %span.Signed-in__content--text メッセージを確認する
          .Signed-in__content
            = link_to "#", class: "Signed-in__content--link" do
              = icon('fas', 'users', class: 'Signed-in__content--icon')
              %span.Signed-in__content--text マイページ
  = render 'layouts/notifications'
  
  = yield
  
  .Footer
    .Center
      .Followus
        ＼ 公式SNSをフォローして最新情報をチェック！／
      .Sns
        = icon('fab', 'twitter-square', class: 'Sns__twitter')
        = icon('fab', 'facebook-square', class: 'Sns__facebook')
      .Menu
        .Menu__text
          はじめての方へ
        .Menu__text
          ご利用ガイド
        .Menu__text
          よくある質問
        .Menu__text
          利用規約
        .Menu__text
          個人情報保護
        .Menu__text
          特定商取引に基づく表記
      .Menu
        .Menu__text
          お問い合わせ
        .Menu__text
          CREED Journal
        .Menu__text
          採用担当者の方
      .Copyright
        © Copyright 2020 BlueBlaze Inc. All Rights Reserved.